resources:
  - name: repo
    type: git
    source:
      uri: "https://github.com/manedurphy/concourse-practice.git"

jobs:
  - name: hello-world-job
    plan:
      - get: repo
        trigger: true
      - task: show-content
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          inputs:
            - name: repo
          run:
            path: cat
            args: ["repo/README.md"]
