resources:
  - name: repo
    type: git
    icon: github
    source:
      uri: https://((github.username)):((github.personal_access_token))@github.com/manedurphy/concourse-practice.git
      branch: main

  - name: repo-image
    type: docker-image
    icon: docker
    source:
      repository: manedurphy/concourse-test
      username: ((docker_hub.username))
      password: ((docker_hub.password))

jobs:
  - name: git-example
    plan:
      - get: repo
        trigger: true
      - task: create-commit
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: gitea/gitea
          inputs:
            - name: repo
          outputs:
            - name: repo
          run:
            path: sh
            args:
              - -cx
              - |
                cd repo
                date +"%Y-%m-%d" > todays-date
                git add ./todays-date
                git config --global user.email ((github.email))
                git config --global user.name ((author))
                git commit -m "Update todays date"
      - put: repo
        params:
          repository: repo
  - name: build-and-push
    plan:
      - get: repo
      - put: repo-image
        params:
          build: repo
